<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>API Panel</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
   
      .container {
        max-width: 960px;
      }

      .border-top { border-top: 1px solid #e5e5e5; }
      .border-bottom { border-bottom: 1px solid #e5e5e5; }
      .border-top-gray { border-top-color: #adb5bd; }

      .box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

      .lh-condensed { line-height: 1.25; }

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      body {
        /* font-size: .875rem; */
        margin-top: 60px; 
      }

      .feather {
        width: 16px;
        height: 16px;
        vertical-align: text-bottom;
      }

      /*
      * Sidebar
      */

      .sidebar {
        position: fixed;
        top: 0;
        bottom: 0;
        left: 0;
        z-index: 100; /* Behind the navbar */
        padding: 48px 0 0; /* Height of navbar */
        box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
      }

      .sidebar-sticky {
        position: relative;
        top: 0;
        height: calc(100vh - 48px);
        padding-top: .5rem;
        overflow-x: hidden;
        overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
      }

      @supports ((position: -webkit-sticky) or (position: sticky)) {
        .sidebar-sticky {
          position: -webkit-sticky;
          position: sticky;
        }
      }

      .sidebar .nav-link {
        font-weight: 500;
        color: #333;
      }

      .sidebar .nav-link .feather {
        margin-right: 4px;
        color: #999;
      }

      .sidebar .nav-link.active {
        color: #007bff;
      }

      .sidebar .nav-link:hover .feather,
      .sidebar .nav-link.active .feather {
        color: inherit;
      }

      .sidebar-heading {
        font-size: .75rem;
        text-transform: uppercase;
      }

      /*
      * Content
      */

      [role="main"] {
        padding-top: 133px; /* Space for fixed navbar */
      }

      @media (min-width: 768px) {
        [role="main"] {
          padding-top: 48px; /* Space for fixed navbar */
        }
      }

      /*
      * Navbar
      */

      .navbar-brand {
        padding-top: .75rem;
        padding-bottom: .75rem;
        font-size: 1rem;
        background-color: rgba(0, 0, 0, .25);
        box-shadow: inset -1px 0 0 rgba(0, 0, 0, .25);
      }

      .navbar .form-control {
        padding: .75rem 1rem;
        border-width: 0;
        border-radius: 0;
      }

      .form-control-dark {
        color: #fff;
        background-color: rgba(255, 255, 255, .1);
        border-color: rgba(255, 255, 255, .1);
      }

      .form-control-dark:focus {
        border-color: transparent;
        box-shadow: 0 0 0 3px rgba(255, 255, 255, .25);
      }

    </style>

  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#" onclick="signOut();">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <h1>CRUD Users</h1>
    <div class="table-responsive">
      <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#addUserModal">Add User</button>
      <table class="table table-striped table-sm" id="table-users">
        <thead>
          <tr>
            <th>Actions</th>
            <th>#</th>
            <th>first_name</th>
            <th>last_name</th>
            <th>email</th>
            <th>password</th>
            <th>cerated_at</th>
            <th>updated_at</th>
          </tr>
        </thead>
        <tbody id="container-table">
        </tbody>
      </table>
    </div>

    <!-- modal -->
    <div class="modal fade" id="addUserModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">New user</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">

            <form id="formAddUser" onsubmit="addUSer(); return false;">
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="firstName">First name</label>
                  <input type="text" class="form-control" id="firstName" placeholder="Jonh" value="" required>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="lastName">Last name</label>
                  <input type="text" class="form-control" id="lastName" placeholder="Doe" value="" required>
                </div>
              </div>
              <div class="mb-3">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" placeholder="you@example.com" required>
              </div>
              <div class="mb-3">
                <label for="username">Password</label>
                <input type="password" class="form-control" id="password" placeholder="secret..." required>
              </div>
              <hr class="mb-4">
              <div class="row justify-content-center">
                <div class="col-auto">
                  <button type="button" id="btn-cancel" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                  <button class="btn btn-primary" type="submit">Add User</button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>



  </div>
</div>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>



    <script>

    $(document).ready(function(){

      getUsers();

    }); // document ready

    function getUsers(){

      $("#container-table").empty();

      var settings = {
        "async": true,
        "crossDomain": true,
        "url": "http://localhost/proyectos/api-slim/public/api/users",
        "method": "GET",
        "headers": {
          "Authorization": "Bearer " + localStorage.token,
          "cache-control": "no-cache"
        }
      }

      $.ajax(settings)
        .done(function (data){
          $.each(data, function(idx, opt) {
            $("#container-table").append('<tr><td class="align-middle"><button type="button" onclick="deleteUser('+opt.id+');" class="btn btn-danger mr-2"><ion-icon name="trash"></button><button type="button" class="btn btn-warning"></ion-icon><ion-icon name="create"></ion-icon></button></td><td class="align-middle">'+opt.id+'</td><td class="align-middle">'+opt.first_name+'</td><td class="align-middle">'+opt.last_name+'</td><td class="align-middle">'+opt.email+'</td><td class="align-middle">'+opt.password+'</td><td class="align-middle">'+opt.created_at+'</td><td class="align-middle">'+opt.updated_at+'</td></tr>');
          });
        })
        .fail(function(jqXHR, textStatus, errorThrown){
          alert('Error: ' + jqXHR.statusText);
          window.location.href="http://localhost/proyectos/api-slim/public/";
        });

    }

    function addUSer(){
      
      var data = JSON.stringify({ 
        firstname : $("#firstName").val(),
        lastname : $("#lastName").val(),
        email : $("#email").val(), 
        password : $("#password").val(),
      });

      var settings = {
        "async": true,
        "crossDomain": true,
        "url": "http://localhost/proyectos/api-slim/public/api/user/add",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json",
          "Authorization": "Bearer " + localStorage.token,
          "cache-control": "no-cache"
        },
        "processData": false,
        "data": data
      }

      $.ajax(settings)
        .done(function (data){
          $("#btn-cancel").click();
          getUsers();
        })
        .fail(function(jqXHR, textStatus, errorThrown){
          alert( "error" );
        });

    }

    function deleteUser(id_user){
      
      var settings = {
        "async": true,
        "crossDomain": true,
        "url": "http://localhost/proyectos/api-slim/public/api/user/delete/" + id_user,
        "method": "DELETE",
        "headers": {
          "Authorization": "Bearer " + localStorage.token,
          "cache-control": "no-cache"
        }
      }

      $.ajax(settings)
        .done(function (data){
          getUsers();
        })
        .fail(function(jqXHR, textStatus, errorThrown){
          alert( "error" );
        });

    }

    function signOut(){
      localStorage.clear();
      window.location.href="http://localhost/proyectos/api-slim/public/";
    }


    </script>
</html>